name: Manual Publish NuGet Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

permissions:
  packages: write
  contents: read

env:
  BSON_PROJECT_PATH: 'src/MongoDB.Bson/MongoDB.Bson.csproj'
  DRIVER_PROJECT_PATH: 'src/MongoDB.Driver/MongoDB.Driver.csproj'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: |
          dotnet restore ${{ env.BSON_PROJECT_PATH }}
          dotnet restore ${{ env.DRIVER_PROJECT_PATH }}

      - name: Build
        run: |
          dotnet build ${{ env.BSON_PROJECT_PATH }} --configuration Release --no-restore
          dotnet build ${{ env.DRIVER_PROJECT_PATH }} --configuration Release --no-restore

      - name: Pack
        run: |
          dotnet pack ${{ env.BSON_PROJECT_PATH }} --configuration Release --no-build -p:PackageVersion=${{ inputs.version }}
          dotnet pack ${{ env.DRIVER_PROJECT_PATH }} --configuration Release --no-build -p:PackageVersion=${{ inputs.version }} -p:Version=${{ inputs.version }} -p:AssemblyVersion=${{ inputs.version }} -p:FileVersion=${{ inputs.version }}

      - name: Push to NuGet
        run: |
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/InsurUp/index.json --skip-duplicate
